ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\felip\AppData\Roaming
CHROME_CRASHPAD_PIPE_NAME=\\.\pipe\crashpad_27008_CCQXMZKHBLIENXWU
COMMONPROGRAMFILES=C:\Program Files\Common Files
COMMONPROGRAMFILES(X86)=C:\Program Files (x86)\Common Files
COMMONPROGRAMW6432=C:\Program Files\Common Files
COMPUTERNAME=BOOK-ULEHC3E8HN
COMSPEC=C:\WINDOWS\system32\cmd.exe
CONDA_PROMPT_MODIFIER=False
CURSOR_TRACE_ID=deb58e2d954c4d8e933bb5da73603ab6
DRIVERDATA=C:\Windows\System32\Drivers\DriverData
EFC_9916_1262719628=1
EFC_9916_1592913036=1
EFC_9916_2775293581=1
EFC_9916_3789132940=1
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
GOPATH=C:\Users\felip\go\
HOMEDRIVE=C:
HOMEPATH=\Users\felip
IGCCSVC_DB=AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAxud2TfaVlECRFHey/dANmwQAAAACAAAAAAAQZgAAAAEAACAAAADYepQMcoBevd5tl/8Mc+aDxi2wrWie2DRaOjG+9drBZwAAAAAOgAAAAAIAACAAAACAFYni5fadCCNitEkQEUMbQ/55EtKbGccvbmi2x0aGVGAAAABVIM7vBR9SOJqLQMlCXrqUj5iYL7OAjqBwQs5QRPbpZrlmfvZpisfb7Mj2KBIVN4QH6i2K/cEmLBjISXaoTu1lqx2PGK8qMGJBhUhBVUJbzP5eiSbq/YW0puOIf36LUq5AAAAAG7bDBRZ37AEQHsQrc0uYov9FKe3F+R1gCfAeJZH/zIPVKJnFVCFg5Kw6oyQxB6XTSbwcYsMRiRjShTb1Uy6PeQ==
LOCALAPPDATA=C:\Users\felip\AppData\Local
LOGONSERVER=\\BOOK-ULEHC3E8HN
NUMBER_OF_PROCESSORS=20
ONEDRIVE=C:\Users\felip\OneDrive
ONEDRIVECONSUMER=C:\Users\felip\OneDrive
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
OS=Windows_NT
PATH=c:\Users\felip\AppData\Local\Programs\cursor\resources\app\bin;C:\Users\felip\AppData\Local\Programs\Opera;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\nodejs\;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\GitHub CLI\;C:\Program Files\CMake\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\felip\scoop\shims;C:\Users\felip\AppData\Local\pnpm;C:\Users\felip\AppData\Local\Programs\Python\Python312\Scripts\;C:\Users\felip\AppData\Local\Programs\Python\Python312\;C:\Users\felip\AppData\Local\Microsoft\WindowsApps;C:\Users\felip\AppData\Roaming\npm;C:\Users\felip\AppDat;c:\Users\felip\AppData\Local\Programs\cursor\resources\app\bin;c:\Users\felip\AppData\Local\Programs\cursor\resources\app\bin;C:\Program Files\TortoiseGit\bin;C:\Program Files\Go\bin;C:\Users\felip\scoop\shims;C:\Users\felip\AppData\Local\pnpm;C:\Users\felip\AppData\Local\Programs\Python\Python312\Scripts\;C:\Users\felip\AppData\Local\Programs\Python\Python312\;C:\Users\felip\AppData\Local\Microsoft\WindowsApps;C:\Users\felip\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\felip\AppData\Roaming\npm;C:\Users\felip\AppData\Local\Programs\Hyper\resources\bin;C:\Users\felip\AppData\Local\Programs\oh-my-posh\bin;C:\Users\felip\go\bin;C:\Program Files\PostgreSQL\17\bin;C:\Users\felip\AppData\Local\Microsoft\WindowsApps;C:\Users\felip\AppData\Local\Programs\cursor\resources\app\bin;C:\Users\felip\AppData\Local\GitHubDesktop\bin;C:\Users\felip\go\bin
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
PNPM_HOME=C:\Users\felip\AppData\Local\pnpm
POSH_CURSOR_COLUMN=1
POSH_CURSOR_LINE=1
POSH_INSTALLER=winget
POSH_SESSION_ID=9482f67e-da16-4004-8b39-8680f84eb02b
POSH_SHELL=pwsh
POSH_SHELL_VERSION=5.1.26100.3624
POSH_THEME=C:\Users\felip\AppData\Local\Programs\oh-my-posh\themes\zash.omp.json
POSH_THEMES_PATH=C:\Users\felip\AppData\Local\Programs\oh-my-posh\themes
POWERLINE_COMMAND=oh-my-posh
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 186 Stepping 2, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=ba02
PROGRAMDATA=C:\ProgramData
PROGRAMFILES=C:\Program Files
PROGRAMFILES(X86)=C:\Program Files (x86)
PROGRAMW6432=C:\Program Files
PSMODULEPATH=C:\Users\felip\OneDrive\Documentos\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
PYENV_VIRTUALENV_DISABLE_PROMPT=1
SESSIONNAME=Console
SYSTEMDRIVE=C:
SYSTEMROOT=C:\WINDOWS
TEMP=C:\Users\felip\AppData\Local\Temp
TMP=C:\Users\felip\AppData\Local\Temp
USERDOMAIN=BOOK-ULEHC3E8HN
USERDOMAIN_ROAMINGPROFILE=BOOK-ULEHC3E8HN
USERNAME=felipeversiane
USERPROFILE=C:\Users\felip
VIRTUAL_ENV_DISABLE_PROMPT=1
WINDIR=C:\WINDOWS
ZES_ENABLE_SYSMAN=1
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=0.49.6
LANG=en_US.UTF-8
COLORTERM=truecolor
GIT_ASKPASS=c:\Users\felip\AppData\Local\Programs\cursor\resources\app\extensions\git\dist\askpass.sh
VSCODE_GIT_ASKPASS_NODE=C:\Users\felip\AppData\Local\Programs\cursor\Cursor.exe
VSCODE_GIT_ASKPASS_EXTRA_ARGS=
VSCODE_GIT_ASKPASS_MAIN=c:\Users\felip\AppData\Local\Programs\cursor\resources\app\extensions\git\dist\askpass-main.js
VSCODE_GIT_IPC_HANDLE=\\.\pipe\vscode-git-0fd87ca593-sock
VSCODE_INJECTION=1
