[run]
timeout = "3m"
tests = true
fast = true
issues-exit-code = 1

[linters]
enable = [
  "govet",
  "errcheck",
  "staticcheck",
  "ineffassign",
  "gosimple",
  "gocritic",
  "unused",
  "gocyclo",
  "gofmt",
  "goimports",
  "revive",
  "typecheck",
  "errchkjson",
  "cyclop",
  "dogsled",
  "dupl",
  "errorlint",
  "exhaustive",
  "exportloopref",
  "funlen",
  "gochecknoglobals",
  "goerr113",
  "gomnd",
  "goprintffuncname",
  "gosec",
  "misspell",
  "nakedret",
  "nestif",
  "nilerr",
  "noctx",
  "nolintlint",
  "prealloc",
  "promlinter",
  "unconvert",
  "unparam",
  "whitespace"
]

[linters-settings.gocyclo]
min-complexity = 15

[linters-settings.funlen]
lines = 100
statements = 50

[linters-settings.revive]
severity = "warning"
confidence = 0.8

[[linters-settings.revive.rules]]
name = "var-naming"

[[linters-settings.revive.rules]]
name = "exported"

[[linters-settings.revive.rules]]
name = "indent-error-flow"

[linters-settings.goimports]
local-prefixes = "github.com/ProjetosCodeTower/donation-server"

[issues.exclude-rules]
[[issues.exclude-rules]]
path = "_test\\.go"
linters = [
  "gochecknoglobals",
  "gosec",
  "funlen",
  "noctx"
]