name: donation-server

services:
  server:
    build: 
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: donation-server
    ports:
      - "8000:8000"
    restart: unless-stopped

networks:
  default:
    driver: bridge