FROM golang:1.24.2-alpine3.20

RUN apk add --no-cache git

RUN go install github.com/cespare/reflex@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["/go/bin/reflex", "-r", "\\.go$", "-s", "-l", "2", "./app"]