FROM golang:1.24.1-alpine3.20

RUN apk add --no-cache git

RUN go install github.com/cosmtrek/air@v1.43.0

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["air", "-c", ".air.toml"] 