name: Continous Integration

on:
  pull_request:
    branches: [main, develop]
    paths-ignore: ["docs/**"]

  push:
    branches: [main, develop]
    paths-ignore: ["docs/**"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Download dependencies
        run: go mod download

      - name: Build the project
        run: make build

      - name: Run the project
        run: make up

  lint:
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Download dependencies
        run: go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1

      - name: Run lint
        run: make lint

  security:
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Download dependencies
        run: go mod download

      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-file: 'go.mod'

  test:
    runs-on: ubuntu-22.04
    needs: [lint, security]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: make test
