name: main

on:
  pull_request:
    branches: [main, develop]
    paths-ignore: ["docs/**"]

  push:
    branches: [main, develop]
    paths-ignore: ["docs/**"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Download dependencies
        run: go mod download

      - name: Build the project
        run: make build

      - name: Run the project
        run: make up

  lint:
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Download dependencies
        run: go mod download

      - name: Install GolangCI-Lint
        run: |
          curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v1.55.2/golangci-lint-1.55.2-linux-amd64.tar.gz | tar -xz -C /tmp
          sudo mv /tmp/golangci-lint-1.55.2-linux-amd64/golangci-lint /usr/local/bin/golangci-lint

      - name: Run Linter 
        run: make lint

  security:
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Download dependencies
        run: make download

      - name: Run Vulnerability detection using govulncheck
        run: make govulncheck

  test:
    runs-on: ubuntu-22.04
    needs: [lint, security]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: make test
